### ISSUE TITLE
按键序列加入侧键的触发

### ISSUE THREAD

**Issue by zaiqixiao** [intmian/quick_skill#14]
能否自定义上下左右绑定，由于某些原因无法使用方向键，游戏中设置的是鼠标X2上，鼠标X1下，左A，右D。

**Comment by intmian** [comment]
什么意思呀，你希望别的键位绑定触发方向键吗

**Comment by zaiqixiao** [comment]
希望可以自定义上下左右的按键绑定，如果能支持鼠标侧键就更好了

**Comment by zaiqixiao** [comment]
可能是我没描述清楚，就是程序里面现在上下左右不是绑定了四个方向键吗，希望可以自定义绑定，比如我在游戏里面上是鼠标侧键X2，下是鼠标侧键X1，左A，右D。因为我键盘没有方向键，修改成方向键的话不方便搓其他球。所以希望可以自定义绑键，不是快捷键绑定上下左右。

**Comment by intmian** [comment]
你的意思是按键序列希望自定义上下左右对应的真实按键是吧。例如目前是上对应↑，你希望改成X2。
这样的话直接填对应的真实按键就行吧，比如你希望“左 右”世界触发“A D”，就按键序列就填“A D”。
当然目前X2、X1都不支持添加到按键序列，有需求的话后面做下

**Comment by zaiqixiao** [comment]
是的，如果后续能支持绑定侧键那就更好了

**Comment by intmian** [comment]
好的，我加入版本计划

**Comment by intmian** [comment]
@zaiqixiao 代码已提交

**Comment by zaiqixiao** [comment]
好的，谢谢佬

**Comment by zaiqixiao** [comment]
![image](https://github.com/user-attachments/assets/7b25f2a4-f96d-4ad5-8d92-df3112091803)
佬，我设置成这样但是在游戏里没法触发对应战备，一开始以为是按键持续时长的问题，但是改到50也不行。但是改成用方向键的话就是正常的。
