### ISSUE TITLE
按键序列中侧键触发在Helldive2中无效以及自制解决办法

### ISSUE THREAD

**Issue by zaiqixiao** [intmian/quick_skill#15]
![image](https://github.com/user-attachments/assets/ad6cb429-5096-4056-a57a-dc7cbec765a0)
佬，我设置成这样但是在游戏里没法触发对应战备，一开始以为是按键持续时长的问题，但是改到50也不行，用鼠标测试软件测试侧键有正常触发并且按下次数也是对的。改成用方向键的话就是正常的。

**Comment by zaiqixiao** [comment]
![image](https://github.com/user-attachments/assets/ffee8886-6a36-4fab-b2a6-d842f373ebdf)
在配置文件中删除延迟运行正常了。

**Comment by intmian** [comment]
你这个现象是正常的，删除掉配置json里面序列的x1、x2的持续时长，和配成0理论上是一致的。我刚刚介入了探测器跑了下，逻辑是完全一致的。如果你通过删除持续时间的方法能够work的话，方便起见可以直接改成0。
因为我早就退坑了，所以手里没有环境测试，我猜测是游戏内的触发逻辑有做时长的校验。

当然无论如何，能解决问题就好

**Comment by zaiqixiao** [comment]
好的谢谢
