### ISSUE TITLE
按上下左右的时候，并没有显示在输入框中

### ISSUE THREAD

**Issue by zjhappy1314** [intmian/quick_skill#3]
如题，好像上下左右没有 效果

**Comment by intmian** [comment]
你好。目前特殊按键（上下左右，鼠标侧键……）还不支持直接捕捉输入呢。如果需要输入上下左右的方向键，请以中文输入（“上”、”下”、”左”、右”之类的）。

非常感谢你的反馈，如果方便能帮忙点个小星星吗，这对于我真的很重要
