### ISSUE TITLE
这个判断有啥用?不让用L和R?

### ISSUE THREAD

**Issue by ShangJunFengg** [intmian/quick_skill#4]
![image](https://github.com/user-attachments/assets/006ec002-4284-43d4-8724-2bc5012ec118)

**Comment by intmian** [comment]
感谢您的反馈
lr被我用来做按住左右键的输入了
您如果需求大的话我可以改下lr放出来，左右键单独处理
顺带一提能帮忙点个星星吗

**Comment by ShangJunFengg** [comment]
我试了下,把这段注释了就可以用了,已点star

**Comment by intmian** [comment]
嗯嗯，有空了我改下。之前自己用没发现这里还挺阴间的

**Comment by intmian** [comment]
已经修复，请参考1.1.1版本
