### ISSUE TITLE
按住触发键，会重复触发连招，但是再按第二个键会结束重复？这是什么机制、如何解决？

### ISSUE THREAD

**Issue by SaiyaFi** [intmian/quick_skill#8]
比如按住触发键K(设置一),使用WASD移动,会失效
即使加上设置组合触发键K+W(设置二),按住K,频繁按下W,(设置一)也会失效,停止循环
有什么方法可以保持循环吗

就是不想K(触发键),受到其他按键影响

**Comment by intmian** [comment]
不好意思，我最近新换了手机没有设置邮箱推送。
我没有很看懂意思。是说如果键盘里有别的按键处于按压状态就会导致触发失败吗

**Comment by SaiyaFi** [comment]
是的,比如我需要一个连招一直触发,所以我一直按着一个键,比如K.
当我需要移动的时候WASD,这个K便会失效,不再处于连招触发.

**Comment by intmian** [comment]
好的，我研究下，有空修复

**Comment by intmian** [comment]
这个修复不了，这个是系统层面的问题。你可以尝试下在不开启软件的时候长按某一个键，此时再按另外一个键，也会打断连击。
![image](https://github.com/user-attachments/assets/f7e0bbf0-4025-493b-ba4f-84a666fbafa5)

我查了资料，这个功能是windows的重复键入功能，目前看没有办法解决这个按第二个键会中断重复键入的问题
![image](https://github.com/user-attachments/assets/b0190cd8-8740-4200-9b5f-1befd62cc6ba)
