### ISSUE TITLE
需要额外触发键:鼠标左键和右键

### ISSUE THREAD

**Issue by SaiyaFi** [intmian/quick_skill#9]
或者已经有这个功能?我该如何设置

**Comment by intmian** [comment]
可以做这个功能，不过左右键不好做类似于ctrl+左键触发的功能，而且左右键会不会误触率很高呢。有需求的话我出个版本更新下

**Comment by SaiyaFi** [comment]
非常有需求,我暂时不需要ctrl+左键触发.
主要我需求右键触发,而且不希望WASD移动或者shift会影响到右键,类似我上个问题.

**Comment by SaiyaFi** [comment]
对了,有做个开关键的想法吗

**Comment by intmian** [comment]
好的，加入开发计划了

**Comment by intmian** [comment]
@SaiyaFi 做完了，下载了最新版本的

**Comment by SaiyaFi** [comment]
点赞,感谢!

**Comment by SaiyaFi** [comment]
刚用txt文档测试了一下,好像左键和右键并不能按住循环,不论点击还是按住只能触发一次.
晚上用游戏再测试一下.

**Comment by SaiyaFi** [comment]
刚测试了一下,鼠标确实不会循环.

**Comment by SaiyaFi** [comment]
我去尝试下另外的工具,试试鼠标连点器,能不能联动

**Comment by intmian** [comment]
因为读的是按键按下的事件，所以是不会自动重放的
